name: test automate

on:
  pull_request:
    branches:
      - 'main'

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./server

      - name: Print working directory
        run: pwd
      
      - name: Print list folder
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
    
      - name: run test
        run: npm run test            